# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DownloadDocount', models.IntegerField(default=0, verbose_name='访问次数')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('Datatime', models.CharField(default='2019-04-22 11:51:24', max_length=32, verbose_name='添加时间')),
                ('path', models.CharField(max_length=32, verbose_name='下载路径')),
                ('name', models.CharField(default='', max_length=32, verbose_name='文件名')),
                ('Filesize', models.CharField(max_length=10, verbose_name='文件大小')),
                ('PCIP', models.CharField(default='', max_length=32, verbose_name='文件IP')),
            ],
            options={
                'verbose_name': 'download',
                'db_table': 'download',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.User'),
        ),
    ]
